name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn package

    - name: Generate JavaDocs
      run: mvn javadoc:javadoc
      working-directory: ./Calculator

    - name: Archive JavaDocs
      uses: actions/upload-artifact@v2
      with:
        name: JavaDocs
        path: Calculator/docs

    - name: Run tests
      run: mvn test
